# Generated by Django 4.1 on 2024-08-16 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HowToCook',
            fields=[
                ('how_to_cook_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingridient_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ingridient_measurement', models.CharField(blank=True, max_length=255, null=True)),
                ('ingridient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ingridient_quantity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level_id', models.AutoField(primary_key=True, serialize=False)),
                ('level_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(blank=True, max_length=255, null=True)),
                ('image_filename', models.TextField(blank=True, null=True)),
                ('time_cook', models.IntegerField(blank=True, null=True)),
                ('ingredient', models.TextField(blank=True, null=True)),
                ('how_to_cook', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_time', models.DateTimeField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='recipes.category')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='recipes.level')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('fullname', models.CharField(blank=True, max_length=255)),
                ('password', models.TextField(blank=True, null=True)),
                ('role', models.CharField(blank=True, default='User', max_length=100, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_time', models.DateTimeField(blank=True, null=True)),
                ('role_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='recipes.role')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingridient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeHowToCook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_to_cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.howtocook')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='recipes.user'),
        ),
        migrations.CreateModel(
            name='FavoriteFoods',
            fields=[
                ('favoritefood_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_favorite', models.BooleanField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_time', models.DateTimeField(blank=True, null=True)),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='recipes.recipe')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='recipes.user')),
            ],
        ),
    ]
